export const items = [
  { name: "Paracetamol", category: "Medicine", price: 20, quantity: 100, supplier: "ABC Pharma", description: "Fever and pain relief medicine" },
  { name: "Syringe", category: "Consumable", price: 10, quantity: 200, supplier: "MedSupply", description: "Sterile disposable syringe" },
  { name: "Gloves", category: "Consumable", price: 5, quantity: 500, supplier: "SafeHands", description: "Medical examination gloves" },
  { name: "Bandage", category: "Consumable", price: 15, quantity: 150, supplier: "HealthCare Ltd", description: "Elastic crepe bandage" },
  { name: "Thermometer", category: "Equipment", price: 250, quantity: 50, supplier: "MedEquip", description: "Digital thermometer" },
  { name: "Stethoscope", category: "Equipment", price: 500, quantity: 30, supplier: "MedEquip", description: "Dual head stethoscope" },
  { name: "IV Drip", category: "Consumable", price: 80, quantity: 120, supplier: "LifeLine", description: "IV infusion set" },
  { name: "Insulin", category: "Medicine", price: 300, quantity: 60, supplier: "DiabetesCare", description: "Insulin injection" },
  { name: "Antibiotic", category: "Medicine", price: 120, quantity: 80, supplier: "ABC Pharma", description: "Broad spectrum antibiotic" },
  { name: "Wheelchair", category: "Equipment", price: 5000, quantity: 10, supplier: "Mobility Inc", description: "Folding wheelchair" },
  { name: "Oxygen Cylinder", category: "Equipment", price: 8000, quantity: 5, supplier: "AirCare", description: "Medical oxygen cylinder" },
  { name: "Face Mask", category: "Consumable", price: 2, quantity: 1000, supplier: "SafeHands", description: "3 ply surgical mask" },
  { name: "Sanitizer", category: "Consumable", price: 50, quantity: 300, supplier: "CleanCare", description: "Alcohol based hand sanitizer" },
  { name: "ECG Machine", category: "Equipment", price: 20000, quantity: 3, supplier: "MedTech", description: "12 lead ECG machine" },
  { name: "X-Ray Film", category: "Consumable", price: 100, quantity: 200, supplier: "Radiant", description: "Medical X-ray film" },
  { name: "Blood Bag", category: "Consumable", price: 150, quantity: 100, supplier: "LifeBank", description: "Blood collection bag" },
  { name: "Scalpel", category: "Equipment", price: 200, quantity: 70, supplier: "SurgiTools", description: "Surgical scalpel" },
  { name: "Surgical Kit", category: "Equipment", price: 1500, quantity: 20, supplier: "SurgiTools", description: "Complete surgical kit" },
  { name: "Vitamin Tablets", category: "Medicine", price: 60, quantity: 90, supplier: "HealthPlus", description: "Multivitamin tablets" },
  { name: "Pain Relief Gel", category: "Medicine", price: 90, quantity: 75, supplier: "ABC Pharma", description: "Topical pain relief gel" },
];